// This file is automatically generated from CMake
#ifndef DART_COMMON_PATHS_H
#define DART_COMMON_PATHS_H

#define DART_ROOT_PATH "/Users/VincentYu/Desktop/dart/"
#define DART_DATA_PATH "/Users/VincentYu/Desktop/dart/data/"

#endif // #ifndef DART_COMMON_PATHS_H
